---
title: "Ambidext"
author: "Anne"
date: "9/28/2020"
output: html_document
---

```{r}
library("WebPower")

wp.mediation(n = NULL, power = 0.8, a = 0.4, b = 0.4, varx = 1,
vary = 1, varm = 1, alpha = 0.05, interval = NULL)

```


```{r loading_packs, eval = T, include = F, echo = F}
knitr::opts_chunk$set(include = F, echo = F, warning = F, message = F)
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

packages <- c("mediation", "foreign", "tidyverse","stargazer","multicon", "ggplot2", "plyr", "reshape2", "readxl", 
              "scales", "grid", "tidyLPA", "Rcpp", "naniar", "dplyr", "car", "mice", 
              "rstudioapi", "labelled", "modi", "semPlot", "kulife")
ipak(packages)

citation()
```

```{r setwd, include = FALSE, echo = FALSE}
library(rstudioapi)
 set_wd <- function() {
   current_path <- getActiveDocumentContext()$path 
   setwd(dirname(current_path ))
   print( getwd() )
 }
 set_wd()
 
 getwd()
```

## Load data 

```{r loading_data, cache = TRUE}

options(knitr.table.format = function() {
  if (knitr::is_latex_output()) 'latex' else 'pandoc'
})

library(rlang)
library(tidyverse)
library(foreign)
files <- dir(paste0(getwd(), "/Data/"), pattern = "\\.sav$", full.names = FALSE) 
df_list <- vector("list", length(files))
names(df_list) <- files
read_in <- function(df = files) {
  for (fname in df) {
    df_list[[fname]] <- haven::read_sav(paste0(getwd(), "/Data/", fname), encoding = NULL, user_na = FALSE, col_select = NULL,skip = 0, n_max = Inf, .name_repair = "unique") 
  }
    names(df_list) <- paste0("", gsub(".sav","",names(df_list)))
    ff <- df_list
}


df_list <- read_in(files)

list2env(df_list,envir=.GlobalEnv)

Ambi <- rbind(`Entrepreneur+Ambidexterity+T1_July+5,+2022_14.32`) 

Ambi <- Ambi %>% select(-matches("IPAddress|Recipient|LocationLatitude|LocationLongitude|ResponseId|T1email_1"))

library(haven)

write_sav(Ambi, "03_Raw_data")

```

